# Generated by Django 3.2 on 2021-04-30 15:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('zipCode', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('state', models.CharField(max_length=200)),
                ('country', models.CharField(max_length=200)),
                ('telefon', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('notes', models.CharField(max_length=200)),
                ('lastAssociation', models.DateField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name='StorageCenters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('zipCode', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='StorageUnits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('size', models.CharField(max_length=200)),
                ('price', models.CharField(max_length=200)),
                ('inService', models.BooleanField(default=True)),
                ('notes', models.CharField(max_length=500)),
                ('rentedToId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storage_renting_app.customers')),
                ('storagecenterId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storage_renting_app.storagecenters')),
            ],
        ),
        migrations.CreateModel(
            name='StorageReservations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.CharField(max_length=500)),
                ('customerId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storage_renting_app.customers')),
                ('storageUnitId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storage_renting_app.storageunits')),
            ],
        ),
    ]
