# Generated by Django 3.2 on 2021-05-04 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storage_renting_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customers',
            old_name='telefon',
            new_name='telephone',
        ),
    ]
