# Generated by Django 3.2 on 2021-05-04 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage_renting_app', '0003_alter_customers_lastassociation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='lastAssociation',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
