# Generated by Django 3.2 on 2021-05-08 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage_renting_app', '0004_alter_customers_lastassociation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storageunits',
            name='price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='storageunits',
            name='size',
            field=models.IntegerField(),
        ),
    ]
