# Generated by Django 3.2 on 2021-05-08 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('storage_renting_app', '0006_auto_20210508_1038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storageunits',
            name='rentedTo',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='storage_renting_app.customers'),
        ),
        migrations.AlterField(
            model_name='storageunits',
            name='storageCenter',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='storage_renting_app.storagecenters'),
        ),
    ]
