# Generated by Django 3.2 on 2021-05-08 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage_renting_app', '0007_auto_20210508_1737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storageunits',
            name='notes',
            field=models.CharField(blank=True, default=None, max_length=500, null=True),
        ),
    ]
