# Generated by Django 3.2 on 2021-05-09 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage_renting_app', '0008_alter_storageunits_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='address',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='customers',
            name='city',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='customers',
            name='country',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='customers',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='customers',
            name='notes',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='customers',
            name='state',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='customers',
            name='telephone',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='customers',
            name='zipCode',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
